name: iot-wsn-mia-defense
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  # Core Python
  - python=3.9
  - pip
  
  # Machine Learning & Deep Learning
  - pytorch=1.13.0
  - torchvision=0.14.0
  - tensorflow=2.11.0
  - cpuonly  # Use this for CPU-only version
  
  # Scientific Computing
  - numpy=1.23.0
  - scipy=1.9.0
  - pandas=1.5.0
  - scikit-learn=1.1.0
  
  # Data Processing
  - opacus=1.4.0
  
  # Network Analysis
  - networkx=2.8.0
  
  # Visualization
  - matplotlib=3.6.0
  - seaborn=0.12.0
  - plotly=5.11.0
  
  # Utilities
  - tqdm=4.64.0
  - pyyaml=6.0
  - joblib=1.2.0
  
  # Jupyter (optional)
  - jupyter=1.0.0
  - ipykernel=6.19.0
  
  # Code Quality
  - black=22.12.0
  - flake8=6.0.0
  - mypy=0.991
  
  # Testing
  - pytest=7.2.0
  - pytest-cov=4.0.0
  
  # Additional pip packages
  - pip:
    - tensorboard==2.11.0
    - torchinfo==1.7.0
